### ISSUE TITLE
[TASK] Fix how h is computed

### ISSUE THREAD

**Issue by guruvamsi-policharla** [webb-tools/zk-SaaS#46]
The current version is insecure because the extended witness is reveal in the clear to the King. The correct way to do this can be found at https://github.com/arkworks-rs/groth16/blob/c7e8adec6101f0c51a042fa73f0e31dc344d1ab4/src/r1cs_to_qap.rs#L150.

- [x] Cleanup the distributed FFT implementation and implement a coset FFT
- [x] Fix how h is computed as described in the arkworks implemenation of groth16

**Comment by shekohex** [comment]
While I do agree, please keep in mind that we do compute it differently per circom backend, which is defined here: https://github.com/arkworks-rs/circom-compat/blob/170b10fc9ed182b5f72ecf379033dda023d0bf07/src/circom/qap.rs#L23 
We should keep both, if they return results differently, should they? The main reason they have two different implementation is that in Circom, the `c` Matric in the `ConstraintMatrices` is always empty https://github.com/arkworks-rs/circom-compat/blob/170b10fc9ed182b5f72ecf379033dda023d0bf07/src/zkey.rs#L192

Different format, same thing.

And for the witness reveal to the king, I implemented it that way (knowing it is not the secure way) because we wanted a PoC. Now it is time to make it secure (by adding randomness?)

**Comment by drewstone** [comment]
If the two implementations need to be different due to circom vs arkworks differences, yes let's add both. Simultaneously, yes let's ensure that both preserve privacy.
